### ISSUE TITLE
Second Time for:  SmallMolecule <treats, disrupts, prevents, affects> PhenotypicFeature (HP:0011015 Abnormal blood glucose concentration)

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/testing#207]
This query was also run on 5/23/2022 as part of issue #203.  The major changes are:

1. ARAGORN - originally returned 0 results, now returns 641
2. xARA - originally returned 3988 results, now returns 5914
3. Unsecret - originally returned results, now errors
4. CHP is now returning an error

**Query:** [Blood_Glucose_Concen.json](https://github.com/NCATSTranslator/testing/blob/main/ars-requests/not-none/1.2/Blood_Glucose_Concen.json)
**PK:** [4b93c698-1206-4657-b42d-f04c6cfde424](https://arax.ncats.io/?r=4b93c698-1206-4657-b42d-f04c6cfde424)

![image](https://user-images.githubusercontent.com/38321826/171682574-593f8b86-c238-4d0f-a81a-610ecbfb894a.png)

**Comment by andrewsu** [comment]
BTE hasn't made any changes since #203 was run.  As @colleenXu [pointed out](https://github.com/NCATSTranslator/testing/issues/203#issuecomment-1135339563) BTE will successful return results if "hyperglycemia" (MONDO:0002909 / UMLS:[C0020456](https://uts.nlm.nih.gov/uts/umls/concept/C0020456) / HP:0003074) is used in the query.  Because we don't have any resources that link to the parent term "Abnormal blood glucose concentration" (HP:0011015; the term used here), and because we have not implemented a generic ontology-based node expansion yet (issue linked in #203), BTE will not return results for this query yet.  (Apologies, I have to miss today's standup  meeting...)

**Comment by sstemann** [comment]
works with HPO in CI
https://ui.ci.transltr.io/main/results?l=Abnormal%20Blood%20Glucose%20Concentration&i=HP:0011015&t=0&q=313574d3-8d3b-446c-97e2-132d1b918bfb
