### ISSUE TITLE
Updated Biolink predicate

### ISSUE THREAD

**Issue by Bassa1** [NCATSTranslator/testing#224]
I was querying with the recent biolink 2.4.8 version predicates, but I could not find these predicates in the ARAX/UI. For example, the predicates for the Multiomics ERH kPs are associated_with_increased_likelihood and associated_with_decreased_likelihood. Here is the screenshot where I try to select the predicate for creative querying 
![image](https://user-images.githubusercontent.com/100380537/183739298-b88ec642-6df9-4a9e-af00-5a0805d8618f.png)
Any suggestion on why I am having this?

**Comment by edeutsch** [comment]
Yes, this is a result of the ARAX UI only showing predicates that are supported by ARAX (according to some possibly-outdated list) rather than all of Biolink. I have added an issue in the ARAX repo:
https://github.com/RTXteam/RTX/issues/1888
It is not a trivial fix and will require some investigation to figure out how to improve this.

There is a box to "Enter custom Predicate" where you can enter other predicates that the ARAX UI doesn't think are currently supported in ARAX.

**Comment by Bassa1** [comment]
Okay
